Repository coiled/benchmarks, pull requests merged in 2022-04, with the labels that each got.

#5 Add h2o benchmarks
  conftest.py
  setup.cfg
  tests/__init__.py
  tests/test_coiled.py
  tests/test_h2o_benchmarks.py
Labels: h2o-benchmark

#36 Basic stability test
  tests/test_shuffle.py
Labels: stability

#88 Update release procedure
  .github/workflows/tests.yml
  README.md
Labels: documentation
